# Generated by Django 4.2.5 on 2023-09-27 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('brightness', models.PositiveIntegerField(default=50)),
                ('schedule_on', models.TimeField(blank=True, null=True)),
                ('schedule_off', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lamps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LampStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('energy_consumption', models.DecimalField(decimal_places=2, max_digits=8)),
                ('usage_duration', models.DurationField()),
                ('lamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='devices.lamp')),
            ],
        ),
    ]
